AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - '**/bin/*'
    - 'spec/dummy/**/*'
    - 'spec/*_helper.rb'
    - '*.gemspec'
    - 'Appraisals'
    - 'Gemfile'

Rails:
  Enabled: true

# Accept single-line methods if they have no body
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Don't require top-level documentation of classes and modules
Documentation:
  Enabled: false

# Allow chaining methods after multi-line blocks
MultilineBlockChain:
  Enabled: false

# Allow using `->` literals for multi-line blocks
Lambda:
  Enabled: false

# Accept both definition styles: nested and compact
ClassAndModuleChildren:
  Enabled: false

# Don't restrict parameter names for single-line blocks
Style/SingleLineBlockParams:
  Enabled: false

# Use `sprintf` instead of `format` and `%`
FormatString:
  EnforcedStyle: sprintf

# Keep every line less than or equal to 80 characters
LineLength:
  Max: 80

# Use "postfix if/unless" when the length exceeds this value
IfUnlessModifier:
  MaxLineLength: 80

# Keep every method less than or equal 20 lines
MethodLength:
  Max: 20

# Keep ABC size in a class less than or equal to 30
# This should be sync with `MethodLength`
Metrics/AbcSize:
  Max: 30

# Keep every class less than or equal to 200 lines
# This should be sync with `MethodLength`
Metrics/ClassLength:
  Max: 200

# Use double quotes for string literals unless they contains escape characters
StringLiterals:
  EnforcedStyle: double_quotes

# Use `raise` instead of `fail` for exceptions
Style/SignalException:
  EnforcedStyle: only_raise 

# Use trailing commas in argument lists
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

# Use trailing commas in array and hash literals
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

# Use parentheses for almost all percent literals
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

# Allow adding `has_` as a prefix of predicate methods
Naming/PredicateName:
  NamePrefixBlacklist:
    - is_
    - have_

# Use `has_xxx?` methods of Hash
Style/PreferredHashMethods:
  EnforcedStyle: verbose
